### ISSUE TITLE
Alfred v4 support

### ISSUE THREAD

**Issue by onedr0p** [lukewaite/alfred-gitlab#20]
Currently this does workflow does not work with Alfred v4

**Comment by lukewaite** [comment]
Are you able to provide more detail? I am running without issues on v4.0.6.

**Comment by onedr0p** [comment]
Since it works fine for you, I will try to reinstall and leave feedback when I am done. Thanks for the quick response!

**Comment by onedr0p** [comment]
Ok, still doesn't work for me.

When I type (for example) `gl` it keeps popping up telling me it's refreshing the repositories.

See this gif...

![image](https://user-images.githubusercontent.com/213795/70658658-67924780-1c2c-11ea-940a-895f9e546ff3.png)

**Comment by lukewaite** [comment]
Did you already configure your key with `glsetkey`?

You can run `gl workflow:openlog` and that should open logs for the background process in your `Console.app`.

**Comment by onedr0p** [comment]
Yes I configured with the glset commands

Here are the error logs:

```logs
12:58:11 gitlab.py:35 INFO     Setting API Key
12:58:12 workflow.py:2266 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/workflow/workflow.py", line 2259, in run
    func(self)
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/update.py", line 41, in main
    projects = wf.cached_data('projects', wrapper, max_age=3600)
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/workflow/workflow.py", line 1890, in cached_data
    data = data_func()
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/update.py", line 39, in wrapper
    return get_projects(api_key, api_url)
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/update.py", line 10, in get_projects
    return get_project_page(api_key, url, 1, [])
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/update.py", line 22, in get_project_page
    result = list + r.json()
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/workflow/web.py", line 271, in json
    return json.loads(self.content, self.encoding or 'utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
12:58:15 update.py:13 INFO     Calling API page 1
12:58:16 workflow.py:2266 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/workflow/workflow.py", line 2259, in run
    func(self)
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/update.py", line 41, in main
    projects = wf.cached_data('projects', wrapper, max_age=3600)
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/workflow/workflow.py", line 1890, in cached_data
    data = data_func()
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/update.py", line 39, in wrapper
    return get_projects(api_key, api_url)
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/update.py", line 10, in get_projects
    return get_project_page(api_key, url, 1, [])
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/update.py", line 22, in get_project_page
    result = list + r.json()
  File "/Users/dbuhl001/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DE653CFA-3B2B-4694-9035-F748BAC353F5/workflow/web.py", line 271, in json
    return json.loads(self.content, self.encoding or 'utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded```

**Comment by lukewaite** [comment]
Are you using hosted GitLab, or are you self hosting?  

If on hosted, can you please try `glseturl https://gitlab.com/api/v4/projects`? I am curious if perhaps the default has not loaded as I use a self-hosted version for work.. that could be the difference.

**Comment by onedr0p** [comment]
Ah, that did it. I use selfhosted as well and providing that `/api/v4/projects` seemed to work /shrug

**Comment by lukewaite** [comment]
@onedr0p To clarify, had you previously called `glseturl` with just the hostname? 

#10 suggested adding auto-detecting that missing, and adding it. Perhaps that is a worthwhile change to implement.

**Comment by onedr0p** [comment]
Yes, I just had the hostname.
