### ISSUE TITLE
Not fetching any gitlab projects projects => update.py gives HTTP Error 308 permanent redirect

### ISSUE THREAD

**Issue by ReinierH** [lukewaite/alfred-gitlab#24]
Hi!

For some reason the gitlab-workflow is unable to fetch my gitlab projects. The interesting thing here is that when I run the update.py script, the request is returning a 308 permanent redirect, which seems to cause the failing project fetching.

>  12:09:02 update.py:13 INFO     Calling API page 1
> 12:09:03 workflow.py:2266 ERROR    HTTP Error 308: Permanent Redirect
> Traceback (most recent call last):
>   File "/Users/reinier/Google Drive/Software/Mac/Backups/Alfred.alfredpreferences/workflows/user.workflow.B62CD0D1-7304-495B-A388-C0982BFE63FA/workflow/workflow.py", line 2259, in run
>     func(self)
>   File "update.py", line 41, in main
>     projects = wf.cached_data('projects', wrapper, max_age=3600)
>   File "/Users/reinier/Google Drive/Software/Mac/Backups/Alfred.alfredpreferences/workflows/user.workflow.B62CD0D1-7304-495B-A388-C0982BFE63FA/workflow/workflow.py", line 1890, in cached_data
>     data = data_func()
>   File "update.py", line 39, in wrapper
>     return get_projects(api_key, api_url)
>   File "update.py", line 10, in get_projects
>     return get_project_page(api_key, url, 1, [])
>   File "update.py", line 19, in get_project_page
>     r.raise_for_status()
>   File "/Users/reinier/Google Drive/Software/Mac/Backups/Alfred.alfredpreferences/workflows/user.workflow.B62CD0D1-7304-495B-A388-C0982BFE63FA/workflow/web.py", line 405, in raise_for_status
>     raise self.error
> HTTPError: HTTP Error 308: Permanent Redirect

**Comment by ReinierH** [comment]
Make sure to use https://gitlab.com/........ not https://www.gitlab.com because this causes a permanent redirect which the code can't handle.
