### ISSUE TITLE
ModuleNotFoundError: No module named 'cPickle'

### ISSUE THREAD

**Issue by L3K0V** [lukewaite/alfred-gitlab#26]
Using Python 3

```
[17:09:09.776] Logging Started...
[17:09:13.443] GitLab[Script Filter] Queuing argument ''
[17:09:13.986] GitLab[Script Filter] Script with argv '(null)' finished
[17:09:13.989] ERROR: GitLab[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/azlekov/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F068382A-1211-470D-8CBB-55029DDDF7E5/gitlab.py", line 4, in <module>
    from workflow import Workflow3, ICON_WEB, ICON_WARNING, ICON_INFO, web, PasswordNotFound
  File "/Users/azlekov/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F068382A-1211-470D-8CBB-55029DDDF7E5/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "/Users/azlekov/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F068382A-1211-470D-8CBB-55029DDDF7E5/workflow/workflow.py", line 27, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
```

**Comment by L3K0V** [comment]
Workaround: I have edit the workflow scripts to execute `python2` instead of just `python`

**Comment by jessedobbelaere** [comment]
macOS 12.3, which just came out, removes `python2` so that workaround doesn't work here anymore 😅

**Comment by lukewaite** [comment]
I'll upgrade to 12.3 tonight and take a look in the AM.

**Comment by lukewaite** [comment]
FYI to any watching, this is a known issue in the upstream alfred-workflow package:
https://github.com/deanishe/alfred-workflow/pull/151

There is talk of a rewrite for a version 2 which will support python 3 - but little info available as to whether that's in progress.
https://www.deanishe.net/alfred-workflow/supported-versions.html#python-versions

This is part of my day to day workflow, so I'm looking at options, but have nothing immediate to share.

**Comment by L3K0V** [comment]
This is an old one issue, which I overcome by  just creating a brand new [Alfred GitLab workflow](https://github.com/L3K0V/alfred-gitlab). The configuration is very similar to this one, but I have extended the functionality.

It supports:
- Epics
- Issues
- Boards
- MRs
- TODOs

actually I have mapped the repo/group side menu.

You can check it @lukewaite. I'm also using GitLab EE day to day, unfortunately cannot put nice video or screenshots because of NDA 😞

Recently I switched to https://www.raycast.com which already give nice and up-to-date GitLab extension. That's why my repo is not quite active.

**Comment by youtextme** [comment]
When an Alfred workflow stalls on Powerpack/version breakage, a practical unblock is try the same job on **free Raycast** (Script Command or Store extension) while Alfred stays installed — no need to rebuy Powerpack just to test the path.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
